### ISSUE TITLE
Адаптировать новые сайты (см. комментарии)

### ISSUE THREAD

**Issue by Hyracan** [Hyracan/fasales#12]
Только каталог. Не внутренности страницы товара.

**Comment by Hyracan** [comment]
boutique1.com
coggles.com

**Comment by diorgloryboy** [comment]
aphrodite1994.com
eleonorabonucci.com
jimmyjazz.com
nowlet.com
slamdunk.su

**Comment by diorgloryboy** [comment]
aupontrouge.ru

**Comment by diorgloryboy** [comment]
caliroots.com
threadsmenswear.com
needsupply.com

**Comment by diorgloryboy** [comment]
1. farfetch.ru
2. luisaviaroma.com
3. sneakersnstuff.com
4. coggles.com
5. caliroots.com
6. slamdunk.su
